### ISSUE TITLE
Switch block in findMaxAvailable in gl3 causes segfault

### ISSUE THREAD

**Issue by graivoron** [mdparker/Derelict3#175]
Platform: Ubuntu 12.04 x86_64
Compiler: DMD64 D Compiler v2.064.2

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000005f57b3 in derelict.opengl3.gl3.DerelictGL3Loader.findMaxAvailable()
    (
    this=<error reading variable: Could not find the frame base for "derelict.opengl3.gl3.DerelictGL3Loader.findMaxAvailable()".>)
    at ../../.dub/packages/derelict-master/import/derelict/opengl3/gl3.d:525
525             switch(major)
(gdb) backtrace
#0  0x00000000005f57b3 in derelict.opengl3.gl3.DerelictGL3Loader.findMaxAvailable() (
    this=<error reading variable: Could not find the frame base for "derelict.opengl3.gl3.DerelictGL3Loader.findMaxAvailable()".>)
    at ../../.dub/packages/derelict-master/import/derelict/opengl3/gl3.d:525
#1  0x00000000005f24f6 in derelict.opengl3.gl3.DerelictGL3Loader.reload() (
    this=<error reading variable: Could not find the frame base for "derelict.opengl3.gl3.DerelictGL3Loader.reload()".>)
    at ../../.dub/packages/derelict-master/import/derelict/opengl3/gl3.d:89
#2  0x000000000058e8c9 in D main (
    args=<error reading variable: Could not find the frame base for "D main".>)
    at source/app.d:132
#3  0x000000000062cd60 in rt.dmain2._d_run_main() ()
#4  0x0000000000000001 in ?? ()
#5  0x00007fffffffdc00 in ?? ()
#6  0x000000000062ccba in rt.dmain2._d_run_main() ()
#7  0x00007fffffffdcd0 in ?? ()
#8  0x00007fffffffdd10 in ?? ()
#9  0x00007fffffffdcf4 in ?? ()
#10 0x00007fffffffddb0 in ?? ()
#11 0x000000000000003c in ?? ()
#12 0x00000000006496c5 in core.sync.mutex.Mutex.lock() ()
#13 0x00007fffffffddb0 in ?? ()
```

P.S. After replacing switch block with specific version ("return GLVersion.GL30" in my case) it worked fine.

**Comment by mdparker** [comment]
I don't know what "could not find the frame base" means. This doesn't help me much. It would be more informative to see a reduced test case that reproduces the problem along with information on how you have compiled both Derelict and your code.

**Comment by graivoron** [comment]
app.d: http://pastebin.com/UMpbhPGG
derelict and glamour as dependencies
dub build does all the job
